runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v4
      id: cache
      with:
        path: |
          pytorch
          .git/modules
        key: pytorch
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "cache missed!"
        git submodule update --init --recursive
        cd pytorch
        git submodule update --remote third_party/pocketfft/
        cd ..
      shell: pwsh
    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          pytorch
          .git/modules
        key: pytorch