name: build
on:
  workflow_dispatch:
    inputs: 
      config:
        type: choice
        required: true
        default: "Debug"
        options:
          - Release
          - Debug
      min:
        type: choice
        required: true
        default: "ON"
        options:
            - ON
            - OFF
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fetch
      - run: python -m pip install -r pyyaml
      - run: ./build.bat ${{ inputs.config }} ${{ inputs.min }}
      - uses: actions/upload-artifact@v4
        with:
          name: libtorch_${{ inputs.config }}_${{ inputs.min }}
          path: pytorch/install/