name: CI
on:
  workflow_dispatch:
    inputs: 
      config:
        type: choice
        required: true
        default: "Debug"
        options:
          - Release
          - Debug
      min:
        type: boolean
        required: true
        default: false
jobs:
  fetch:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            pytorch
            .git/modules
          key: pytorch
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "cache missed!"
          git submodule update --init --recursive
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            pytorch
            .git/modules
          key: pytorch
  build:
    needs: fetch
    runs-on: windows-2022
    steps:
      - run: build.bat ${{ inputs.config }}
      - uses: action/upload-artifact@v4
        with:
          name: libtorch_${{ inputs.config }}_${{ inputs.min }}
          path: pytorch/install/