name: CI
on:
  workflow_dispatch:
jobs:
  fetch:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: ./pytorch
          key: pytorch
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "cache missed!"
          git submodule update --init --recursive
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ./pytorch
          key: pytorch